### ISSUE TITLE
Packets out of order

### ISSUE THREAD

**Issue by ZoumiSurGithub** [poggit/libasynql#101] opened 2023-07-21 12:59 UTC
**Describe the bug**
It seems to happen when there hasn't been any requests for a while and then suddenly there are a lot.

**Error on console:**
Fatal error: Uncaught ErrorException: Packets out of order. Expected 1 received 0. Packet size=145 in /home/zoumi/kitmap/plugins/Network/src/poggit/libasynql/mysqli/MysqliThread.php:96
Stack trace:
#0 [internal function]: pocketmine\errorhandler\ErrorToExceptionHandler::handle(2, 'Packets out of ...', '/home/zoumi/kit...', 96)
#1 /home/zoumi/kitmap/plugins/Network/src/poggit/libasynql/mysqli/MysqliThread.php(96): mysqli->ping()
#2 /home/zoumi/kitmap/plugins/Network/src/poggit/libasynql/base/SqlSlaveThread.php(86): poggit\libasynql\mysqli\MysqliThread->executeQuery(Object(mysqli), 1, 'UPDATE players\n...', Array)
#3 phar:///home/zoumi/kitmap/PocketMine-MP.phar/src/thread/CommonThreadPartsTrait.php(96): poggit\libasynql\base\SqlSlaveThread->onRun()
#4 [internal function]: pocketmine\thread\Thread->run()
#5 {main}

**Sample code**

**Expected behavior**

**Environment**
OS: Debian 11
PocketMine version: 5.3.2

**Comment by SOF3** [comment] 2023-07-23 09:17
Basically poor error handling of libasynql. Duplicate of #85.

**Closed as not planned by SOF3** 2023-07-23 09:17 UTC

**Comment by ZoumiSurGithub** [comment] 2023-07-24 21:25
> Basically poor error handling of libasynql. Duplicate of #85.

but after a while, the data is no longer saved, so how can I force the connection to mysql again? and redo the previous queries?

**Comment by SOF3** [comment] 2023-07-25 00:33
libasynql doesn't do anything with your data. if the query was successful initially, its durability it's the responsibility of MySQL unless you deleted the data.

**Comment by ZoumiSurGithub** [comment] 2023-07-25 00:43
let me explain, after a while I get an error with the ping, and it doesn't want to resume the connection with the server until I restart the server, which causes me to lose data, or maybe it's the waitAll I'm doing that's causing this.

**Comment by SOF3** [comment] 2023-07-25 01:57
Yeah, poor error handling in libasynql, let's track this in #85.
